name: moodo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.8.1 <4.0.0' # Memastikan kompatibilitas SDK

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  table_calendar: ^3.1.2
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.1
  google_fonts: ^6.1.0
  image_picker: ^1.0.7 # Untuk memilih gambar dari galeri atau kamera
  path_provider: ^2.1.3 # Untuk mendapatkan direktori penyimpanan di perangkat
  path: ^1.9.0
  pdf: ^3.10.8 # Untuk fitur PDF
  printing: ^5.14.0 # Untuk mencetak/share PDF
  open_file: ^3.3.2 # Untuk membuka file PDF

  # <<-- DEPENDENSI UNTUK NOTIFIKASI -->>
  flutter_local_notifications: ^17.1.2 # Versi stabil yang sudah kita sepakati
  timezone: ^0.9.3 # Penting untuk penjadwalan notifikasi zona waktu
  # <<-- AKHIR DEPENDENSI NOTIFIKASI -->>

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/fonts/Nunito-Regular.ttf
    - assets/fonts/Nunito-Bold.ttf

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700